title: "Anurag Tiwari | AI/ML & Data Analytics Portfolio"
description: "Machine Learning • Data Analytics • Model Deployment"
theme: jekyll-theme-minimal

logo: /assets/profile.jpg
show_downloads: false

linkedin: "www.linkedin.com/in/anurag092"
github: "https://github.com/iamanurag092"
email: "iamanuragt092@gmail.com"
